### PR TITLE
Make it packageable

### PR DESCRIPTION
**Pull request by R0dn3yS**
Move everything from packages.py to the main file so the main file can be placed in $PATH without it needing packages.py

### CODE REVIEW

**Comment by SpyHoodle** [comment]
This has been discussed by me and @Minion3665 privately, but we think that it would be better to have the code itself as separate files, especially as more and more modules (system info such as ) get added.

If it's possible to make it packageable without the need to put everything in one file, depending on how difficult this may be the best solution.

Mini has also suggested a build action, which would automatically put everything into one file, potentially into a branch which is specifically for the AUR.

I'll see what Mini thinks as I'm relatively new to this whole thing.

**Comment by R0dn3yS** [comment]
I can also maintain my fork for the aur with everything in one file there, the package is already on my fork so that would help prevent conflicts as well with updates

**Review by Minion3665 — CHANGES_REQUESTED** [review]
It'd be better not to keep everything in one file; the python interpreter accepts zip files with the entry point called `__main__.py`. Could we use this functionality instead?

**Comment by Minion3665** [comment]
This PR has been superseded by discussion in #8; if the solution there isn't viable, please discuss it there before reopening this pull request

**Pull request closed without merging**
